### ISSUE TITLE
Prepare unity project

### ISSUE THREAD

**Issue by TRG-T** [J-A-F/DECREE#1]
As above. Within this task you should create the main scene, the player model (temporarily a capsule) and configure the project options.

**Comment by TotalLolFace** [comment]
Important things:
Please keep the Player as a prefab in the whole project. When creating movement system, it will be really nice if the Player would be configured as parent of the main camera. Why? In the every new scene we can drop the Player prefab (which will include camera child) with one click and everything is going to be properly configured.
